-- suggested-prices-config.lua
-- Auto-generated by src/generate_suggested_prices_config.ts
-- mined resource base cost = 10
-- production factor = 1.1
return {
  ["coal"] = 10,
  ["copper-cable"] = 6,
  ["copper-ore"] = 10,
  ["copper-plate"] = 11,
  ["crude-oil"] = 10,
  ["electronic-circuit"] = 32,
  ["inserter"] = 74,
  ["iron-chest"] = 97,
  ["iron-gear-wheel"] = 24,
  ["iron-ore"] = 10,
  ["iron-plate"] = 11,
  ["satellite"] = 20328,
  ["solar-panel"] = 922,
  ["steel-chest"] = 532,
  ["steel-plate"] = 61,
  ["stone"] = 10,
  ["transport-belt"] = 19,
  ["wood"] = 10,
  ["wooden-chest"] = 22,
}
